mangalarga:
  ros__parameters:

    # Global
    timeout: 1800
    timeout_per_state: 300
    px_threshold: 50
    max_altitude: 7.0
    safe_altitude: 3.0

    # Initialize
    drone_type: 'mavros'

    model_source: 'best.pt'
    confidence_threshold: 0.5

    image_source: 'realsense'

    # Takeoff
    takeoff_altitude: 1.2  # m

    # Inspect - Windown
    room_x: 10.0
    room_y: 2.0

    # Find Windown
    find_tolerance: 2
    back_speed: -0.5

    # GoToLandingBase
    fixed_base_x: 0.0
    fixed_base_y: 2.0
    mobile_base_x: 0.0
    mobile_base_y: -2.0

    # Precise Landing - Center
    lost_tolerance: 10
    land_altitude: 1.0
    land_speed: -0.5

    # PID xy
    controller_xy_kp: 1.0
    controller_xy_kd: 1.0
    controller_xy_ki: 1.0
    controller_xy_output_min: -1.0
    controller_xy_output_max: 1.0
    controller_xy_integral_min: -1.0
    controller_xy_integral_max: 1.0

    # PID z
    controller_z_kp: 1.0
    controller_z_kd: 1.0
    controller_z_ki: 1.0
    controller_z_output_min: -1.0
    controller_z_output_max: 1.0
    controller_z_integral_min: -1.0
    controller_z_integral_max: 1.0
